from core.types import Price, Quantity

DEFAULT_INITIAL_CASH = Price(1_000_000.0)
DEFAULT_INITIAL_POSITION = Quantity(0)
DEFAULT_POSITION_LIMIT = Quantity(200)
DEFAULT_MAX_ORDER_SIZE = Quantity(10)
DEFAULT_PRUNE_AGE = 5

